// AUTO-GENERATED by scripts/optimize-aquarelles.mjs — do not edit by hand.
export type AquarelleType = "insecte" | "fleur" | "cocktail" | "composition";

export interface Aquarelle {
  id: string;
  type: AquarelleType;
  width: number;
  height: number;
  src: string;         // default WebP (800w or largest)
  srcPng: string;      // PNG fallback
  srcGhost: string;    // ghost WebP
  srcGhostPng: string; // ghost PNG fallback
  srcSet: string;      // responsive WebP srcset
  srcSetGhost: string; // responsive WebP srcset (ghost)
}

const W = [200,400,800] as const;

function build(id: string, type: AquarelleType, width: number, height: number): Aquarelle {
  const base = `/aquarelles/optimized/${id}`;
  const widths = W.filter((w) => w <= width);
  const top = widths[widths.length - 1] ?? width;
  const set = (suffix: string) =>
    widths.map((w) => `${base}${suffix}-${w}.webp ${w}w`).join(", ");
  return {
    id, type, width, height,
    src: `${base}-${top}.webp`,
    srcPng: `${base}-${top}.png`,
    srcGhost: `${base}-ghost-${top}.webp`,
    srcGhostPng: `${base}-ghost-${top}.png`,
    srcSet: set(""),
    srcSetGhost: set("-ghost"),
  };
}

export const AQUARELLES: Aquarelle[] = [
  build("abeille-fleur", "composition", 2265, 2476),
  build("dahlia", "fleur", 1911, 2870),
  build("bouquet-coccinelle", "composition", 2459, 3336),
  build("cocktail-orange", "cocktail", 2181, 2714),
  build("abeille", "insecte", 1066, 1071),
  build("coccinelle", "insecte", 894, 946),
  build("cocktail-grenade", "cocktail", 2002, 2650),
  build("cocktail-citron", "cocktail", 2324, 3130),
];

export const byType = (t: AquarelleType) => AQUARELLES.filter((a) => a.type === t);
